name: pwru-log
description: 'Collect and upload pwru logs'
inputs:
  testname:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Fetch PWRU logs
      shell: bash
      run: |
        set -x

        pods=$(kubectl get pods --selector name=pwru -o go-template='{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
        for pod in $pods; do
          kubectl logs $pod
          kubectl cp $pod:/tmp/pwru.log "$pod.${{ inputs.testname }}.log" || true
        done

    - name: Upload PWRU logs
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: pwru-log
        path: pwru*.log
        retention-days: 5
