name: PWRU Test

inputs:
  test-name:
    required: true
    type: string
  pwru-flags:
    required: false
    type: string
  pwru-pcap-filter:
    required: false
    type: string
  setup:
    required: false
    type: string
  gen-traffic:
    required: false
    type: string
  expected-output-pattern:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: PWRU test
      uses: cilium/little-vm-helper@3b6f374a9b62e6987efee7e3ab226f968d857c7c # v0.0.25
      with:
        provision: 'false'
        cmd: |
          set -x

          ${{ inputs.setup }}

          /host/pwru/pwru \
            --output-tuple \
            --output-file=/tmp/pwru-${{ inputs.test-name }}.log \
            --ready-file=/tmp/pwru-${{ inputs.test-name }}.ready \
            ${{ inputs.pwru-flags }} \
            '${{ inputs.pwru-pcap-filter }}' \
            2>/tmp/pwru-${{ inputs.test-name }}.status &
          PWRU_PID=\$!

          while [ ! -f /tmp/pwru-${{ inputs.test-name }}.ready ]; do sleep 1; done

          ${{ inputs.gen-traffic }}

          kill \$PWRU_PID
          wait \$PWRU_PID

          grep -P '${{ inputs.expected-output-pattern }}' /tmp/pwru-${{ inputs.test-name }}.log

    - name: Fetch artifacts from LVH VM
      if: ${{ !success() }}
      uses: cilium/little-vm-helper@3b6f374a9b62e6987efee7e3ab226f968d857c7c # v0.0.25
      with:
        provision: 'false'
        cmd: |
          mkdir -p /host/logs/${{ inputs.test-name }}
          cp /tmp/pwru-* /host/logs/${{ inputs.test-name }}

    - name: Upload artifacts
      if: ${{ !success() }}
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ inputs.test-name }}
        path: ./logs/${{ inputs.test-name }}/pwru-*
