name: PWRU Test

inputs:
  test-name:
    required: true
    type: string
  pwru-flags:
    required: false
    type: string
  pwru-pcap-filter:
    required: false
    type: string
  traffic-setup:
    required: false
    type: string
  expected-output-pattern:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: PWRU test
      uses: cilium/little-vm-helper@9d758b756305e83718a51b792a5aeabd022a39ec # v0.0.16
      with:
        provision: 'false'
        cmd: |
          set -x

          /host/pwru/pwru \
            --output-tuple \
            --output-file=/tmp/pwru-${{ inputs.test-name }}.log \
            --ready-file=/tmp/pwru-${{ inputs.test-name }}.ready \
            ${{ inputs.pwru-flags }} \
            '${{ inputs.pwru-pcap-filter }}' \
            2>/tmp/pwru-${{ inputs.test-name }}.status &
          PWRU_PID=\$!

          while [ ! -f /tmp/pwru-${{ inputs.test-name }}.ready ]; do sleep 1; done

          ${{ inputs.traffic-setup }}

          kill \$PWRU_PID
          wait \$PWRU_PID

          grep -P '${{ inputs.expected-output-pattern }}' /tmp/pwru-${{ inputs.test-name }}.log

    - name: Upload artifacts
      if: ${{ !success() }}
      uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
      with:
        name: logs-${{ inputs.test-name }}
        path: /tmp/pwru-*
